### ISSUE TITLE
PDF broken

### ISSUE THREAD

**Issue by ecsfang** [openenergymonitor/emontx-3phase#12]
I'm not able to open the PDF-file (emontx-3-phase-userguide.pdf) anymore.
The previous version was ok, but not the latest.

BR/Thomas

**Comment by glynhudson** [comment]
PDF looks ok here. What's the issue your having? 

https://github.com/openenergymonitor/emontx-3phase/blob/master/emontx-3-phase-userguide.pdf

**Comment by danbates2** [comment]
Shows up as blank pages for me also.

**Comment by ecsfang** [comment]
On my Ubuntu 16.04 machine and Chrome it just shows blank pages, and if I download the file, it just says unknown format when trying to open it. And on my phone I just get jidderish.

**Comment by glynhudson** [comment]
Apologies, I see the issue. It's now been fixed :+1:
